services:
  # Frontend Web Service
  - type: web
    name: nyumbakumi-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_BACKEND_URL
        fromService:
          name: nyumbakumi-backend
          type: web
          property: url

  # Backend Web Service
  - type: web
    name: crimereport-kenya-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: FIREBASE_ADMIN_CREDENTIALS
        sync: false # This will be set manually in Render dashboard
      - key: EMAIL_SERVICE
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_SECURE
        value: "true"
      - key: EMAIL_FROM
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_EMAILS
        sync: false
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true 