services:
  - type: web
    name: crimereport-kenya-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: EMAIL_SERVICE
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_EMAILS
        sync: false
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /api/email/status
    autoDeploy: true 